- hosts: sut-kafka-nodes[0]
  tasks:
  - name: "Create  Kafka Topics"
    shell: "( {{bdbench_install_dir}}/bin/create-kafka-topics.sh )"
    async: 10
    poll: 10

- hosts: sut
  tasks:
  - name: "Start Jolokia"
    shell: "( {{bdbench_install_dir}}/bin/start-jolokia-agent.sh )"
    async: 10
    poll: 10
    become: yes
    ignore_errors: yes

- hosts: sut
  tasks:
  - name: "Start Metricbeat"
    shell: "( {{bdbench_install_dir}}/bin/start-metricbeat.sh )"
    async: 10
    poll: 10

- hosts: sut-spark-nodes[0]
  tasks:
  - name: "Start spark job 1"
    shell: "( {{bdbench_install_dir}}/bin/start-spark-job-1.sh )"
    async: 10
    poll: 10

- hosts: sut-spark-nodes[0]
  tasks:
  - name: "Start spark job 3"
    shell: "( {{bdbench_install_dir}}/bin/start-spark-job-3.sh )"
    async: 10
    poll: 10