- hosts: sut
  tasks:
  - name: "Start Jolokia"
    shell: "( {{babel_install_dir}}/bin/start-jolokia-agent.sh )"
    async: 10
    poll: 10
    become: yes
    ignore_errors: yes

- hosts: sut
  tasks:
  - name: "Start Metricbeat"
    shell: "( {{babel_install_dir}}/bin/start-metricbeat.sh )"
    async: 10
    poll: 10
    ignore_errors: yes
    tags: metrics
