#- hosts: node1
#  roles:
#     - { role: java.install}

- hosts: all
  tasks:
      - name: create the bdbench dir {{parent_dir}}
        file:
          path: '{{ parent_dir }}'
          state: directory
          recurse: yes
          mode: '0777'
        become: yes

- hosts: all
  roles:
     - { role: java.install}


- hosts: kafka-nodes
  roles:
     - { role: kafka.install, when: embedded_kafka}

- hosts: elasticsearch-nodes
  roles:
     - { role: elasticsearch.install, when: embedded_elasticsearch}


- hosts: logstash-nodes
  roles:
     - { role: logstash.install, when: embedded_logstash}

- hosts: kibana-nodes
  roles:
     - { role: kibana.install, when: embedded_kibana}

- hosts: all
  roles:
     - { role: bdbench.install}

- hosts: sut
  roles:
     - { role: examples.lambda.install}