
- hosts: sut
  roles:
     - { role: examples.lambda.install}

- hosts: sut-kafka-nodes[0]
  tasks:
  - name: "Create  Kafka Topics"
    shell: "( {{babel_install_dir}}/bin/create-kafka-topics.sh )"
    async: 10
    poll: 10

- hosts: sut-spark-nodes[0]
  tasks:
  - name: "Start spark job 1"
    shell: "( {{babel_install_dir}}/bin/start-spark-job-1.sh )"
    async: 20
    poll: 10
    ignore_errors: yes
    tags: spark

- hosts: sut-spark-nodes[0]
  tasks:
  - name: "Start spark job 3"
    shell: "( {{babel_install_dir}}/bin/start-spark-job-3.sh )"
    async: 20
    poll: 10
    ignore_errors: yes
    tags: spark