---
- name: check for kibana installation..
  stat:
    path: '{{kibana_install_dir}}'
  changed_when: false
  register: kibana_binary
- when: not kibana_binary.stat.exists
  block:
    - name: download kibana tgz...
      get_url:
        url: '{{kibana_tgz_url}}'
        dest: /tmp/{{kibana_tgz}}
        mode: '0644'
        timeout: '{{kibana_download_timeout_seconds}}'
    - name: 'ensure {{kibana_install_parent_dir}} exists'
      file:
        path: '{{kibana_install_parent_dir}}'
        state: directory
        mode: '0755'
    - name: unarchive...
      shell: tar xvf /tmp/{{kibana_tgz}} -C {{kibana_install_parent_dir}}

    - name: copy template...
      template:
        src: kibana.yml.j2
        dest: "{{kibana_install_dir}}/config/kibana.yml"

  always:
    - name: delete archive...
      file:
        path: /tmp/{{kibana_tgz}}
        state: absent


- name: link...
  file:
    src: '{{kibana_install_dir}}'
    dest: '{{kibana_install_link_dir}}'
    state: link
